### ISSUE TITLE
Alias for docker

### ISSUE THREAD

**Issue by Nicolas01** [matt9ucci/DockerCompletion#1]
I use an alias for docker:  
`New-Alias d docker`
When I use my alias the completion doesn't work anymore.  
Do you know what should I have to modify to have the completion working with my alias?

**Comment by matt9ucci** [comment]
Try to execute `Import-Module DockerCompletion` or `Import-Module DockerCompletion -Force` after `New-Alias d docker`.

DockerCompletion registers `docker` and its aliases during execution of `Import-Module`.

**Comment by Nicolas01** [comment]
Excellent! It's exactly what I need.  
Thanks a lot!
