### ISSUE TITLE
Add Support for Compose V2

### ISSUE THREAD

**Issue by allout58** [matt9ucci/DockerCompletion#15]
The new `docker compose` command integrates `docker-compose` into the main `docker` command. See https://docs.docker.com/compose/cli-command/ for details.

I realize this is asking for basically a whole other application to be integrated, so this might not be worth the effort, but discovered this when I installed this module today.

**Comment by matt9ucci** [comment]
Thank you for your comment. [I am considering adding support for Compose V2](https://github.com/matt9ucci/DockerComposeCompletion/issues/1), but it is still pre-release version. [Its 1st release candidate](https://github.com/docker/compose-cli/releases/tag/v2.0.0-rc.1) has just been published a few days ago. Let me wait and see please🙂

**Comment by matt9ucci** [comment]
New version published: [DockerCompletion 1.2010.1.211002](https://www.powershellgallery.com/packages/DockerCompletion/1.2010.1.211002)
In this version, the new `docker compose` command, [GA announcement on Sep 30 2021](https://www.docker.com/blog/docker-desktop-4-1-release-volume-management-now-included-with-docker-personal/), is supported.

Thank you for waiting @allout58
