### ISSUE TITLE
Installation not working

### ISSUE THREAD

**Issue by MarounMaroun** [matt9ucci/DockerCompletion#19]
Any ideas why I'm unable to install the module?

I'm able to find it:

```powershell
>find-Module DockerCompletion

Version              Name                                Repository           Description
-------              ----                                ----------           -----------
1.2300.0.230804      DockerCompletion                    PSGallery            Docker command completion for PowerShell.
```

However, installation doesn't show any progress, it simply ends immediately, and then importing shows that module doesn't exist:

```powershell
>Install-Module DockerCompletion # I tried with and without '-Scope CurrentUser'
>Import-module DockerCompletion
Import-Module: The specified module 'DockerCompletion' was not loaded because no valid module file was found in any module directory.
```

Poweshell version:

```powershell
>$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by matt9ucci** [comment]
Would you try the following?:
* `Get-Module -Name DockerCompletion -ListAvailable | Format-List` : it will display the information of `DockerCompletion` if the module is installed successfully
* `$env:PSModulePath` : it will display the locations that are searched to find modules and resources ([about_PSModulePath](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_psmodulepath?view=powershell-7.4))

**Comment by matt9ucci** [comment]
@MarounMaroun Does that help you in any way?

**Comment by matt9ucci** [comment]
Closing the issue because of no response. If you have more questions, don't hesitate to reopen it.
