### ISSUE TITLE
Why does your Windows Powershell ISE display a list of parameters?

### ISSUE THREAD

**Issue by chrsas** [matt9ucci/DockerCompletion#3]
Why does your Windows Powershell ISE display a list of parameters? In my ISE, I can only loop parameter by Tab.
Windows: 10
Powershell: 5.1

**Comment by matt9ucci** [comment]
The reason why is because I hit Ctrl+Space. Try Ctrl+Space instead of Tab and see "[#PSTip Tab complete properties](https://www.powershellmagazine.com/2016/10/31/pstip-tab-complete-properties/)" in the PowerShell Magazine.

**Comment by chrsas** [comment]
@matt9ucci Thank you.
