### ISSUE TITLE
New GIF demo

### ISSUE THREAD

**Issue by matt9ucci** [matt9ucci/DockerCompletion#4]
Delete the current [demo](https://github.com/matt9ucci/DockerCompletion/blob/694533e9f8d2899f4e6ad4ba98daea60e1079dae/demo.gif) and create a new one.

### Mandatory
* Use PowerShell Core, not ISE
* Use `docker` as the name of docker cli
* Show completion for management commands
* Show completion for subcommands
* Show completion for options
* Show completion for command/option arguments 

### Optional
* ~~Use `d` as the alias of docker cli (in this case, add an another file like "demo-alias.gif")~~
* Show "Tab" being pressed at least once to clarify how to trigger completion
* Show "Ctrl + Space" being pressed at least once to clarify how to trigger completion as a list

**Comment by dima-matsola** [comment]
+1 for alias completion.

I suspect that I can achieve that creating ps1 file with content similar to completers.ps1 but having `Register-Completer d ($managementCommands + $topLevelCommands)` and than adding it as custom completion with -ArgumentList

Right?

-
Update: no I cant :)

**Comment by matt9ucci** [comment]
> I suspect that I can achieve that creating ps1 file

You do not need to do that  :)
Please check the issue #1

**Comment by dima-matsola** [comment]
oh, niiiice! thanks!

**Comment by NikoTurunen** [comment]
Any clue why this works only right after installation, but doesnt work anymore if I restart powershell?

**Comment by matt9ucci** [comment]
@NikoTurunen Did you run `Import-Module DockerCompletion` after restarting powershell?

**Comment by NikoTurunen** [comment]
> @NikoTurunen Did you run `Import-Module DockerCompletion` after restarting powershell?

Actually I didnt. Think if I add this to profile.ps1 file, it should work automatically.

**Comment by matt9ucci** [comment]
@NikoTurunen Try to run `Get-Module DockerCompletion` after restarting powershell. The output will be:

```
PS> Get-Module DockerCompletion

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.1903.0.… DockerCompletion
```

If not, the DockerCompletion module is not imported in your current powershell session. Try to check your profile.ps1 file or run `Import-Module DockerCompletion` manually.

**Comment by NikoTurunen** [comment]
> @NikoTurunen Try to run `Get-Module DockerCompletion` after restarting powershell. The output will be:
> 
> ```
> PS> Get-Module DockerCompletion
> 
> ModuleType Version    Name                                ExportedCommands
> ---------- -------    ----                                ----------------
> Script     1.1903.0.… DockerCompletion
> ```
> 
> If not, the DockerCompletion module is not imported in your current powershell session. Try to check your profile.ps1 file or run `Import-Module DockerCompletion` manually.

Thank you for quick responses. I got it working now. I added :
`Import-Module DockerCompletion`
to my profile.ps1 file.

**Comment by dzmitry-lahoda** [comment]
please update to new slick and nice Windows Terminal OR WSL2 (better to do both - to make linux people to shit onto pwsh:) )
