### ISSUE TITLE
How to get started on Windows 10

### ISSUE THREAD

**Issue by mommaroodles** [matt9ucci/DockerCompletion#5]
I have successfully installed this as per your instructions and not matter whether I use PS or PS administrator or PS ISE or PS ISE admin - there is just nothing! I'm thinking there must be some step that connects what I've downloaded to the PS - I'm on the verge of just deleting this as I'm on a wild goose chase trying to get this to work.

**Comment by matt9ucci** [comment]
> there is just nothing!

Any error messages?

**Comment by matt9ucci** [comment]
I will close this issue because of no response. If you have more questions, don't hesitate to reopen this issue, but please clarify what your environment is and what you did in detail (cmdlets, error/warning/info messages, etc.).

**Comment by mommaroodles** [comment]
Hi Sorry Matt - I didnt even notice the the reply - there was no error messages at all - nothing to indicate that there could be a problem

**Comment by matt9ucci** [comment]
Very little information...  :sweat_smile:

Didn't you forget to run `Import-Module DockerCompletion` ? You can add the command to your [profile](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-6). Otherwise, you should run the command every time after opening a new PowerShell window.

**Comment by stewart-southwell** [comment]
I just want to add that I have the same issue.  

The module s installed in my user profile.  It does show up when I search for it with get-module but I get no autocomplete out of it.  Also, no errors show up.

I am running Powershell  5.1.18362.145 and docker version 19.03.2 on Windows 10.

Does this module support version 19 yet of Docker?

Thanks!

**Comment by matt9ucci** [comment]
@stewart-southwell Version 19 is supported.

Would you check again the [Requirements](https://github.com/matt9ucci/DockerCompletion#requirements), [Quick Start](https://github.com/matt9ucci/DockerCompletion#quick-start), and [Less Quick Start](https://github.com/matt9ucci/DockerCompletion#less-quick-start-without-install-module) sections in the README file?

If it does not solve your problem, please open a new issue and show the followings:

1. The output of `Get-Command docker` 
2. The output of `Get-Module DockerCompletion`
