### ISSUE TITLE
Execution policy error when running Import-Module cmdlet

### ISSUE THREAD

**Issue by marcusjwhelan** [matt9ucci/DockerCompletion#6]
Hello, I try to do this but I am at my company computer and cannot install this because running scripts are disabled on my system.

Is there any work around for this? I get to the step `Get-Module -ListAvailable DockerCompletion` without any problems when running powershell as admin but when I run the `Import-Module DockerCompletion` command I get 

```
Import-Module : File C:\Users\{{User}}\Documents\WindowsPowerShell\Modules\DockerCompletion\NativeCommandCompletio
n\NativeCommandCompletion.psm1 cannot be loaded because running scripts is disabled on this system. For more
information, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ Import-Module DockerCompletion
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [Import-Module], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess,Microsoft.PowerShell.Commands.ImportModuleCommand
```

**Comment by matt9ucci** [comment]
Try to set PowerShell's execution policy to RemoteSigned **for the current user**:

```powershell
Set-ExecutionPolicy RemoteSigned -Scope CurrentUser
```

To display the current execution policy, use the following command:

```powershell
Get-ExecutionPolicy -List
```

The output will be:

```output
        Scope ExecutionPolicy
        ----- ---------------
MachinePolicy       Undefined
   UserPolicy       Undefined
      Process       Undefined
  CurrentUser    RemoteSigned
 LocalMachine      Restricted
```

See also: [about_Execution_Policies](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies)

**Comment by marcusjwhelan** [comment]
Thanks - I also had to enable script on my machine as well.

**Comment by NormanEdance** [comment]
The theme of the issue is kinda confusing. It should be smthing like "**Import-Module confilcts with Execution Policies**" 😄 .
Maybe add this issue to readme.
And don't try `AllSigned` (like I did before found this issue). It won't work, cuz it's not digitally signed.

### Info docs:

- [About Execution Policies](https:/go.microsoft.com/fwlink/?LinkID=135170), 

- [Set-ExecutionPolicy](https://docs.microsoft.com/ru-ru/powershell/module/microsoft.powershell.security/set-executionpolicy?view=powershell-7)

**Comment by matt9ucci** [comment]
@NormanEdance Thank you for your comment. I have fixed the title: "Execution policy error when running Import-Module cmdlet".
