### ISSUE TITLE
How to schedule the import module in windows 10?

### ISSUE THREAD

**Issue by Sanketh-Learning-Tech** [matt9ucci/DockerCompletion#7]
I have to import DockerCompletion module everytime I open PS. Is there a way to schedule the import so that I don't have to manually import everytime I open PS?

**Comment by SANKETH52** [comment]
I have to import DockerCompletion module everytime I open PS. Is there a way to schedule the import so that I don't have to manually import everytime I open PS?

**Comment by matt9ucci** [comment]
@SANKETH52 PowerShell profile is useful in that case. Try the following steps:

1. Create your PS profile file
2. Add `Import-Module DockerCompletion` to the profile file
3. Open PS again

To show the location of your profile file, run the following command:

```powershell
PS> $PROFILE
C:\Users\<your user name>\Documents\PowerShell\Microsoft.PowerShell_profile.ps1
```

The `$PROFILE` is a PowerShell's [automatic variable](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_automatic_variables#profile). For more information, see [About Profiles](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles) in the Microsoft Docs.

**Comment by matt9ucci** [comment]
Closing the issue because of no response. If you have more questions, don't hesitate to reopen it.
