### ISSUE TITLE
Add completer: network disconnect

### ISSUE THREAD

**Issue by doubleUTF** [matt9ucci/DockerCompletion#8]
I've followed the quick steps of installing DockerCompletion and although sometimes it works properly, other times autocomplete populates with values from the directory instead of docker command context. For example if I try to run `docker network disconnect` and try to Tab or Ctrl+Space, I get file values from the current path instead.
![autocomplete_incorrect](https://user-images.githubusercontent.com/17230520/84857995-1fab0d80-b01f-11ea-8fff-8422dc8c6b09.png)
![autocomplete_incorrect2](https://user-images.githubusercontent.com/17230520/84857996-1fab0d80-b01f-11ea-8863-102ede4c2c90.jpg)

**Comment by matt9ucci** [comment]
Thank you for reporting the issue! When we get file values from the current path, there are three possible cases:

1. The BUG
In this case, there is a completer for the command in [completers.ps1](https://github.com/matt9ucci/DockerCompletion/blob/master/DockerCompletion/completers.ps1) or [completers4arguments.ps1](https://github.com/matt9ucci/DockerCompletion/blob/master/DockerCompletion/completers4arguments.ps1) but it does not work well.

2. No result of completer
In this case, there is a completer and it works well, but the result has nothing.

3. No completer for the command
In this case, I will add a new completer as possible if someone opens an issue. (contributions welcome!)

There is no completer for the `docker network disconnect`, therefore it is the case 3. I have just written a new completer and committed it. See the commit 8dbe1ed

**Comment by doubleUTF** [comment]
Thank you @matt9ucci for addressing this issue. Will this commit be published to PS Repository soon?

**Comment by matt9ucci** [comment]
Published the new version https://www.powershellgallery.com/packages/DockerCompletion/1.1903.0.200618
Please check it out. It includes the completer for `docker network disconnect` and the others (e.g. `context` command).

**Comment by doubleUTF** [comment]
Awesome, got it and works great! Thank you for your prompt responsiveness!
