### ISSUE TITLE
One dash (-) and double dash (--) do not work

### ISSUE THREAD

**Issue by dzmitry-lahoda** [matt9ucci/DockerCompletion#9]

**Comment by matt9ucci** [comment]
The `--` and `-` works on my machine. The version is:
* Windows Terminal: 1.3.2651.0
* PowerShell: 7.0.3

I think there are two possible causes for your problem:

1. PowerShell is old
  The DockerCompletion uses `Register-ArgumentCompleter` cmdlet internally. It does not work well for `--` and `-` in Windows PowerShell 5.1 and earlier versions. See the issue  https://github.com/PowerShell/PowerShell/issues/2912 . 

2. PSReadLine is old
  The above issue derives from the old version of PSReadLine.

Please check the version of PowerShell and PSReadLine on your Windows Terminal and update to the newer version.

**Comment by dzmitry-lahoda** [comment]
yes.

is it possible to show warning during install or import about that in old ps shell? or prevent installing into old ps?

**Comment by matt9ucci** [comment]
`PowerShellVersion = '5.0'` is set in the manifest file (DockerCompletion.psd1). The setting prevents importing in the Windows PowerShell 4.0 or earlier.

I will not bump up the `PowerShellVersion = '5.0'` to 7 or higher until PowerShell Core become the default shell for Windows.

**Comment by dzmitry-lahoda** [comment]
I see. Anyway just may be put -- - issue higher in readme. Thanks.
